### ISSUE TITLE
no .exe file

### ISSUE THREAD

**Issue by mariq12341234** [kuronekozero/AnkiVocabHelper#16]
i don't see any .exe file inside of the Zip, am I missing something?

**Comment by kuronekozero** [comment]
.exe file should be inside of "gui" folder.
You also should install AnkiVocabHelper.rar instead of zip source code.

**Comment by mariq12341234** [comment]
how to install .rar? i see .zip archive only

**Comment by mariq12341234** [comment]
![Screenshot 2024-05-05 at 5 04 18 PM](https://github.com/kuronekozero/AnkiVocabHelper/assets/139960191/6b4667c1-6208-4ed3-aee0-cbca81e2b812)

same as i simply rename it

**Comment by kuronekozero** [comment]
open the repository, after that go to releases page and download the latest version of .rar file.
![image](https://github.com/kuronekozero/AnkiVocabHelper/assets/80159807/dde23df9-fff4-4d00-828c-0b99ebefbe30)
